# Generated by Django 2.2.7 on 2020-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0004_auto_20191108_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
