# Generated by Django 2.2.7 on 2020-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0005_remove_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='reset_password_token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
