# Generated by Django 2.2.7 on 2020-01-24 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0006_useraccount_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='token_sent_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
