# Generated by Django 2.2.7 on 2020-01-25 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0007_useraccount_token_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='token_sent_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
