# Generated by Django 2.2.7 on 2020-01-25 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0008_auto_20200125_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='token_sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
