# Generated by Django 2.2.7 on 2020-01-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0009_auto_20200125_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='username',
        ),
    ]
