# Generated by Django 2.2.7 on 2020-01-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anima_app', '0010_auto_20200125_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='name',
        ),
    ]
